### ISSUE TITLE
Better location for the config file (Windows only ?)

### ISSUE THREAD

**Issue by Overengined** [Syycorax/gofork#4]
Why on earth would one want to put the config file in XXXXX\AppData\Roaming\gofork (on windows) ? It's making finding it and tweaking or just deleting it manually after being created more complicated. Yes the path is displyed, but once only, right fater the creation of said config file, so that doesn't count. 
I suggest that the file should be stored in the same folder as the executable, so that it is easier to find and therefore easier to change manually.

**Comment by Yaya-Cout** [comment]
Why would you like to edit config file ?

**Comment by Overengined** [comment]
1. Because it's a config file, it has to be easily editable.
2. Because when removing the app, that would leave behind the file with the PAT, as with both in the same folder, you just delete the folder and "voilà".
3. If you don't want use the app to change it.

**Comment by Syycorax** [comment]
I agree that the in the current state, finding and editing (?) the config file may be kinda tricky.
Despite that, I don't really understand why one would need to edit the config file, as "config file" is just a fancy way to say that gofork need to store the PAT which would not need to be changed in the intended use of the program. 

While your point for deleting is still standing, I think that I used the recommended method and path given the name of the function used:
```golang
os.UserConfigDir()
```
If you have a piece of documentation that suggest otherwise, I'll be happy to read it and implement its solution, as I've struggled myself to find the right way to do it
I will anyway think of how to manage the config file in a better way.

**Comment by Overengined** [comment]
Bear with me a bit because I might be hopelessly boring here.
For comparison here, I'm going to use another open-source project that turned out well so I can make my points clearer : [Minetest](https://github.com/minetest/minetest).

So while I consider that the reasons I invoked in my first message are still valid, I also want you to think in the future, where there might be more than one parameter (potentially a lot, who knows ?) stored in that config file. Maybe forks of your project will have to store data on the config file ? Then it seem sobvious for me that you would want to have an easy access on it. Minetest by example made theirs super accessible by putting it in the main game directory. So for me it's good to have the config file in the app direcotory for future expansion and ease of reuse.

Regarding your will to be provided doc backing my sayings, I must sadly tell you that I haven't got any right at hand, as working with the config file in the app directory is more of a nice and practical convention I've witnessed around somes small and medium projects and been advised about orally by fellow coders. 

But of course, I would fully understand that you would not want to move this file. But then **please** find a way to make that file deletable from within the app at any point (maybe by adding a command in the app ?) as it contains for now (I'm aware you're actively working on this issue) a **plaintext PAT**.

**Comment by Yaya-Cout** [comment]
The problem, if the config path is stored in the current directory, is that you need a new config time on each folder.

**Comment by Syycorax** [comment]
I don't think your example, as popular as it might be, is relevant there.
While Minetest stores their config file in the root folder, `minetest.conf.example` contains 3,5k+ lines. I'm pretty confident in the fact that gofork won't ever have that tremendous amount of parameters to edit, neither in a fork nor in the main repo. 

> "So for me it's good to have the config file in the app directory for future expansion and ease of reuse."

Let's imagine the config file is in the gofork folder. If you delete the gofork folder, your PAT is lost, and you have to re-generate a new one, as GitHub allow only one time access to PATs.

Now with the config file in the AppData. If you delete the gofork folder, your PAT is still stored, which is perfect for ease of reuse. 
Plus, you can clone multiple gofork folder (ex: one for upstream and one for the fork you are working on) and only have to fill PAT once. And there is no point using 2 different PATs.

Lastly, as for the PAT being stored in plaintext, the user is being told to use a PAT **without any scope** which only allow read-only access to **public information** as you can see [here](https://docs.github.com/en/developers/apps/building-oauth-apps/scopes-for-oauth-apps)

As a final point, the option to delete the PAT from the tool directly is WIP

**Comment by Yaya-Cout** [comment]
And, if you want extra security, you can set an expiration date for your token (I use a 30 days token).

**Comment by apoleon33** [comment]
> And, if you want extra security, you can set an expiration date for your token (I use a 30 days token).

Your token expire, my gofork will still work without touching it even if I die, we are not the same 

*insert Gustavo meme*

**Comment by Syycorax** [comment]
An option to delete config was added with e10f3d9d9869bbf5b2ef013dcc48f62918ba092d

**Comment by Overengined** [comment]
Taking in account these changes, I consider that this issue has been succesfully taken in account by the devs and I therefor choose to close this issue.
